export const APP_URL = "http://localhost:3000";

export type TExpirationLength = {
  caption: string;
  value: number;
};

export const EXPIRATION_LENGTHS: Array<TExpirationLength> = [
  { caption: "1 minute", value: 60 * 1000 },
  { caption: "5 minutes", value: 5 * 60 * 1000 },
  { caption: "10 minutes", value: 10 * 60 * 1000 },
  { caption: "30 minutes", value: 30 * 60 * 1000 },
  { caption: "1 hour", value: 60 * 60 * 1000 },
  { caption: "12 hours", value: 12 * 60 * 60 * 1000 },
  { caption: "1 day", value: 24 * 60 * 60 * 1000 },
  { caption: "1 week", value: 7 * 24 * 60 * 60 * 1000 },
  { caption: "2 weeks", value: 2 * 7 * 24 * 60 * 60 * 1000 },
  { caption: "1 month", value: 4 * 7 * 24 * 60 * 60 * 1000 },
  { caption: "6 months", value: 6 * 4 * 7 * 24 * 60 * 60 * 1000 },
  { caption: "1 year", value: 12 * 4 * 7 * 24 * 60 * 60 * 1000 },
];

export type TLanguage = {
  caption: string;
  value: string;
};

export const LANGUAGES: Array<TLanguage> = [
  { caption: "Raw", value: "raw" },
  { caption: "MarkDown", value: "markdown" },
  { caption: "1C", value: "1c" },
  { caption: "ABNF", value: "abnf" },
  { caption: "Access logs", value: "accesslog" },
  { caption: "ActionScript", value: "actionscript" },
  { caption: "Ada", value: "ada" },
  { caption: "AngelScript", value: "angelscript" },
  { caption: "Apache", value: "apache" },
  { caption: "AppleScript", value: "applescript" },
  { caption: "Arcade", value: "arcade" },
  { caption: "Arduino (C++ w/Arduino libs)", value: "arduino" },
  { caption: "ARM assembler", value: "armasm" },
  { caption: "AsciiDoc", value: "asciidoc" },
  { caption: "AspectJ", value: "aspectj" },
  { caption: "AutoHotkey", value: "autohotkey" },
  { caption: "AutoIt", value: "autoit" },
  { caption: "AVR assembler", value: "avrasm" },
  { caption: "Awk", value: "awk" },
  { caption: "X++", value: "axapta" },
  { caption: "Bash", value: "bash" },
  { caption: "Basic", value: "basic" },
  { caption: "BNF", value: "bnf" },
  { caption: "Brainfuck", value: "brainfuck" },
  { caption: "C", value: "c" },
  { caption: "C/AL", value: "cal" },
  { caption: "Cap’n Proto", value: "capnproto" },
  { caption: "Clojure", value: "clojure" },
  { caption: "CMake", value: "cmake" },
  { caption: "CoffeeScript", value: "coffeescript" },
  { caption: "Coq", value: "coq" },
  { caption: "Cache Object Script", value: "cos" },
  { caption: "C++", value: "cpp" },
  { caption: "Crmsh", value: "crmsh" },
  { caption: "Crystal", value: "crystal" },
  { caption: "C#", value: "csharp" },
  { caption: "CSP", value: "csp" },
  { caption: "CSS", value: "css" },
  { caption: "D", value: "d" },
  { caption: "Dart", value: "dart" },
  { caption: "Diff", value: "diff" },
  { caption: "Django", value: "django" },
  { caption: "DNS Zone file", value: "dns" },
  { caption: "Dockerfile", value: "dockerfile" },
  { caption: "DOS", value: "dos" },
  { caption: "Delphi", value: "dpr" },
  { caption: "dsconfig", value: "dsconfig" },
  { caption: "DTS (Device Tree)", value: "dts" },
  { caption: "Dust", value: "dust" },
  { caption: "EBNF", value: "ebnf" },
  { caption: "Elixir", value: "elixir" },
  { caption: "Elm", value: "elm" },
  { caption: "Erlang", value: "erlang" },
  { caption: "Excel", value: "excel" },
  { caption: "FIX", value: "fix" },
  { caption: "Fortran", value: "fortran" },
  { caption: "F#", value: "fsharp" },
  { caption: "Gams", value: "gams" },
  { caption: "GAUSS", value: "gauss" },
  { caption: "G-Code", value: "gcode" },
  { caption: "Gherkin", value: "gherkin" },
  { caption: "OpenGL Shading Language", value: "glsl" },
  { caption: "Go", value: "go" },
  { caption: "Golo", value: "golo" },
  { caption: "Gradle", value: "gradle" },
  { caption: "Roboconf", value: "graph" },
  { caption: "Groovy", value: "groovy" },
  { caption: "Haml", value: "haml" },
  { caption: "Handlebars", value: "handlebars" },
  { caption: "Haskell", value: "haskell" },
  { caption: "Haxe", value: "haxe" },
  { caption: "HTTP", value: "http" },
  { caption: "Hy", value: "hy" },
  { caption: "Inform7", value: "inform7" },
  { caption: "Ini, TOML", value: "ini" },
  { caption: "IRPF90", value: "irpf90" },
  { caption: "Java", value: "java" },
  { caption: "JavaScript", value: "javascript" },
  { caption: "JSON", value: "json" },
  { caption: "Julia", value: "julia" },
  { caption: "Q", value: "k" },
  { caption: "Kotlin", value: "kotlin" },
  { caption: "Lasso", value: "lasso" },
  { caption: "LDIF", value: "ldif" },
  { caption: "Leaf", value: "leaf" },
  { caption: "Less", value: "less" },
  { caption: "Lisp", value: "lisp" },
  { caption: "LiveCode Server", value: "livecodeserver" },
  { caption: "LiveScript", value: "livescript" },
  { caption: "Lua", value: "lua" },
  { caption: "Makefile", value: "makefile" },
  { caption: "Mathematica", value: "mathematica" },
  { caption: "Matlab", value: "matlab" },
  { caption: "Maxima", value: "maxima" },
  { caption: "Maya Embedded Language", value: "mel" },
  { caption: "Mercury", value: "mercury" },
  { caption: "Mizar", value: "mizar" },
  { caption: "Mojolicious", value: "mojolicious" },
  { caption: "Monkey", value: "monkey" },
  { caption: "Moonscript", value: "moonscript" },
  { caption: "N1QL", value: "n1ql" },
  { caption: "Nginx", value: "nginx" },
  { caption: "Nim", value: "nim" },
  { caption: "Nix", value: "nix" },
  { caption: "NSIS", value: "nsis" },
  { caption: "Objective C", value: "objectivec" },
  { caption: "OCaml", value: "ocaml" },
  { caption: "OpenSCAD", value: "openscad" },
  { caption: "Oxygene", value: "oxygene" },
  { caption: "STEP Part 21", value: "p21" },
  { caption: "Parser3", value: "parser3" },
  { caption: "Perl", value: "perl" },
  { caption: "PF", value: "pf" },
  { caption: "PostgreSQL & PL/pgSQL", value: "pgsql" },
  { caption: "PHP", value: "php" },
  { caption: "Plaintext", value: "plaintext" },
  { caption: "Pony", value: "pony" },
  { caption: "PowerShell", value: "powershell" },
  { caption: "Processing", value: "processing" },
  { caption: "Python profiler results", value: "profile" },
  { caption: "Prolog", value: "prolog" },
  { caption: "Properties", value: "properties" },
  { caption: "Protocol Buffers", value: "protobuf" },
  { caption: "Puppet", value: "puppet" },
  { caption: "Python REPL", value: "python-repl" },
  { caption: "Python", value: "python" },
  { caption: "QML", value: "qml" },
  { caption: "R", value: "r" },
  { caption: "ReasonML", value: "reasonml" },
  { caption: "RenderMan RIB", value: "rib" },
  { caption: "RenderMan RSL", value: "rsl" },
  { caption: "Ruby", value: "ruby" },
  { caption: "Oracle Rules Language", value: "ruleslanguage" },
  { caption: "Rust", value: "rust" },
  { caption: "SAS", value: "SAS" },
  { caption: "Scala", value: "scala" },
  { caption: "Scheme", value: "scheme" },
  { caption: "Scilab", value: "scilab" },
  { caption: "SCSS", value: "scss" },
  { caption: "Shell", value: "shell" },
  { caption: "Smali", value: "smali" },
  { caption: "Smalltalk", value: "smalltalk" },
  { caption: "SML", value: "sml" },
  { caption: "SQL", value: "sql" },
  { caption: "Stan", value: "stan" },
  { caption: "Stata", value: "stata" },
  { caption: "Stylus", value: "stylus" },
  { caption: "SubUnit", value: "subunit" },
  { caption: "Swift", value: "swift" },
  { caption: "Test Anything Protocol", value: "tap" },
  { caption: "Tcl", value: "tcl" },
  { caption: "LaTeX", value: "tex" },
  { caption: "Thrift", value: "thrift" },
  { caption: "TP", value: "tp" },
  { caption: "Twig", value: "twig" },
  { caption: "TypeScript", value: "typescript" },
  { caption: "Vala", value: "vala" },
  { caption: "VB.Net", value: "vbnet" },
  { caption: "VBScript", value: "vbscript" },
  { caption: "Verilog", value: "verilog" },
  { caption: "VHDL", value: "vhdl" },
  { caption: "Vim Script", value: "vim" },
  { caption: "x86 Assembly", value: "x86asm" },
  { caption: "XL", value: "xl" },
  { caption: "HTML, XML", value: "xml" },
  { caption: "XQuery", value: "xquery" },
  { caption: "YAML", value: "yml" },
  { caption: "Zephir", value: "zephir" },
];
